# Generated by Django 5.2.17 on 2026-09-01 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mikhmon_instance_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        max_digits=10,
                        verbose_name="Prix d'une instance Mikhmon (FCFA)",
                    ),
                ),
                (
                    "router_monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        max_digits=10,
                        verbose_name="Prix mensuel par routeur (FCFA)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Tarifaire",
                "verbose_name_plural": "Configuration Tarifaire",
            },
        ),
    ]
