# Generated by Django 5.2.17 on 2026-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_platformsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsetting",
            name="mikhmon_base_domain",
            field=models.CharField(
                default="mikroot.net",
                help_text="Ex: mikroot.net (les sous-domaines seront https://espace.mikroot.net)",
                max_length=100,
                verbose_name="Domaine de base Mikhmon",
            ),
        ),
    ]
