# Generated by Django 5.2.17 on 2026-09-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_platformsetting_mikhmon_base_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsetting",
            name="mikhmon_base_domain",
            field=models.CharField(
                default="mikroot.app",
                help_text="Ex: mikroot.app (les sous-domaines seront https://espace.mikroot.app)",
                max_length=100,
                verbose_name="Domaine de base Mikhmon",
            ),
        ),
    ]
