# Generated by Django 5.2.17 on 2026-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Administrateur"),
                    ("TECHNICIAN", "Technicien / Installateur"),
                    ("OWNER", "Propriétaire WiFi Zone"),
                ],
                default="OWNER",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
