# Generated by Django 5.2.17 on 2026-09-01 20:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom du routeur"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("EXPIRED", "Expiré"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "price_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        max_digits=10,
                        verbose_name="Prix mensuel (FCFA)",
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, verbose_name="Renouvellement automatique"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Date d'expiration")),
                (
                    "last_ping",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier Ping VPN"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "mikhmon_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routers",
                        to="instances.mikhmoninstance",
                        verbose_name="Instance Mikhmon liée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Routeur MikroTik",
                "verbose_name_plural": "Routeurs MikroTik",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VpnCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vpn_server",
                    models.CharField(
                        default="vpn.mondomaine.com",
                        max_length=100,
                        verbose_name="Serveur VPN",
                    ),
                ),
                (
                    "vpn_user",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Utilisateur VPN"
                    ),
                ),
                (
                    "vpn_password",
                    models.CharField(max_length=64, verbose_name="Mot de passe VPN"),
                ),
                (
                    "assigned_ip",
                    models.GenericIPAddressField(
                        protocol="IPv4", verbose_name="IP VPN Assignée (10.8.0.x)"
                    ),
                ),
                (
                    "api_port",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Port API Distant"
                    ),
                ),
                (
                    "winbox_port",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Port Winbox Distant"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "router",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_credential",
                        to="routers.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identifiant VPN",
                "verbose_name_plural": "Identifiants VPN",
            },
        ),
    ]
