# Generated by Django 5.2.17 on 2026-09-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0001_initial"),
        ("routers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpncredential",
            name="wireguard_listen_port",
            field=models.PositiveIntegerField(
                default=13231, verbose_name="Port d'écoute WireGuard"
            ),
        ),
        migrations.AddField(
            model_name="vpncredential",
            name="wireguard_private_key",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Clé Privée WireGuard"
            ),
        ),
        migrations.AddField(
            model_name="vpncredential",
            name="wireguard_public_key",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Clé Publique WireGuard"
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name="router",
            name="last_ping",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernier contact"
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="mikhmon_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routers",
                to="instances.mikhmoninstance",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom du Routeur"),
        ),
        migrations.AlterField(
            model_name="router",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="vpncredential",
            name="vpn_password",
            field=models.CharField(max_length=64, verbose_name="Mot de passe VPN L2TP"),
        ),
        migrations.AlterField(
            model_name="vpncredential",
            name="vpn_user",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Utilisateur VPN L2TP"
            ),
        ),
    ]
