# Generated by Django 5.2.17 on 2026-09-01 20:37

import apps.instances.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MikhmonInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: siramanass (donnera siramanass.wifizonevpn.net ou votre domaine)",
                        max_length=63,
                        unique=True,
                        validators=[apps.instances.models.validate_subdomain_name],
                        verbose_name="Nom du Mikhmon (Sous-domaine)",
                    ),
                ),
                (
                    "routeros_version",
                    models.CharField(
                        choices=[
                            ("V6", "RouterOS v6 (6.1 - 6.49)"),
                            ("V7", "RouterOS v7 (7.10 - 7.16+ Recommandé)"),
                        ],
                        default="V7",
                        max_length=10,
                        verbose_name="Version RouterOS",
                    ),
                ),
                (
                    "admin_user",
                    models.CharField(
                        default="admin",
                        max_length=50,
                        verbose_name="Nom d'utilisateur Mikhmon",
                    ),
                ),
                (
                    "admin_password",
                    models.CharField(
                        default="mikroot2026",
                        max_length=100,
                        verbose_name="Mot de passe Mikhmon",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'achat"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mikhmon_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Mikhmon",
                "verbose_name_plural": "Instances Mikhmon",
                "ordering": ["-created_at"],
            },
        ),
    ]
